import { Request, Response } from 'express';

// Note: Database types (Query, Statistic) are now auto-generated by Prisma
// Import from '@prisma/client' when needed

// swapi.tech response types (native format)
export interface SwapiSearchResponse<T> {
  message: string;
  result: Array<{
    uid: string;
    properties: T;
    description: string;
  }>;
}

export interface SwapiDetailResponse<T> {
  message: string;
  result: {
    uid: string;
    properties: T;
    description: string;
  };
}

// Person properties (inside result.properties)
export interface SwapiPerson {
  name: string;
  height: string;
  mass: string;
  hair_color: string;
  skin_color: string;
  eye_color: string;
  birth_year: string;
  gender: string;
  homeworld: string;
  films: string[];
  species: string[];
  vehicles: string[];
  starships: string[];
  created: string;
  edited: string;
  url: string;
}

// Film properties (inside result.properties)
export interface SwapiFilm {
  title: string;
  episode_id: number;
  opening_crawl: string;
  director: string;
  producer: string;
  release_date: string;
  characters: string[];
  planets: string[];
  starships: string[];
  vehicles: string[];
  species: string[];
  created: string;
  edited: string;
  url: string;
}

// Hydrated types (with expanded nested data)
export interface SwapiPersonWithFilms extends SwapiPerson {
  filmsData: SwapiFilm[];
}

export interface SwapiFilmWithCharacters extends SwapiFilm {
  charactersData: SwapiPerson[];
}

// Top query for statistics
export interface TopQuery {
  search_term: string;
  count: string;
  percentage: string;
}

// Statistics response
export interface StatisticsData {
  topQueries: TopQuery[];
  avgResponseTime: number;
  mostPopularHour: number;
  totalQueries: number;
  computedAt?: Date;
}

// Express handler type
export type ExpressHandler = (req: Request, res: Response) => Promise<void> | void;
